### ISSUE TITLE
APE17 - cookiecutter fails step 0 - example setup.py?

### ISSUE THREAD

**Issue by HeloiseS** [astropy/astropy-APEs#57]
Hello,

trying to do the migration in APE17: https://docs.astropy.org/projects/package-template/en/latest/ape17.html#step-rerender

Step 0 fails - badly for me - I checked if i could do this import in my interpreter and I have no issue so i don't know what's gone wrong
```
Traceback (most recent call last):
  File "/tmp/tmpnubQPB.py", line 5, in <module>
    import urllib.request
ImportError: No module named request
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
```

Anyways, since i don't have my new shiny setup.py is it fine to use the astropy one as a basis?

**Comment by astrofrog** [comment]
@HeloiseS - just to check, are you using Python 2.7? If so, can you try using Python 3.6 or later?

**Comment by HeloiseS** [comment]
Thanks! I'm using 3.6.9 :)

**Comment by astrofrog** [comment]
@HeloiseS - ok thanks for checking, can you try again as I think I've removed the offending import (which wasn't needed)

**Comment by astrofrog** [comment]
(Just FYI I'm transferring the issue to the package-template repository)

**Comment by HeloiseS** [comment]
Thanks I re-ran cookie cutter and now I get the follow :/

```
Traceback (most recent call last):
  File "/tmp/tmpAG7jlI.py", line 46, in <module>
    remove_file('.rtd-environment.yml')
  File "/tmp/tmpAG7jlI.py", line 8, in remove_file
    os.remove(os.path.join(PROJECT_DIRECTORY, filepath))
OSError: [Errno 2] No such file or directory: '/home/fste075/my_package_tmp/hoki/.rtd-environment.yml'
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```
